p = audiorecorder(44100,16,1);
recordblocking(p,1);
play(p);
Ch_three20= getaudiodata(p);
save('./Recognition/Ch_all2.mat','Ch_one1','Ch_one2','Ch_one3','Ch_one4','Ch_one5','Ch_one6',...
                        'Ch_one7','Ch_one8','Ch_one9','Ch_one10','Ch_one11','Ch_one12',...
                        'Ch_one13','Ch_one14','Ch_one15','Ch_one16','Ch_one17','Ch_one18',...
                        'Ch_one19','Ch_one20',...
                        'Ch_two1','Ch_two2','Ch_two3','Ch_two4','Ch_two5','Ch_two6',...
                        'Ch_two7','Ch_two8','Ch_two9','Ch_two10','Ch_two11','Ch_two12',...
                        'Ch_two13','Ch_two14','Ch_two15','Ch_two16','Ch_two17','Ch_two18',...
                        'Ch_two19','Ch_two20',...
                        'Ch_three1','Ch_three2','Ch_three3','Ch_three4','Ch_three5','Ch_three6',...
                        'Ch_three7','Ch_three8','Ch_three9','Ch_three10','Ch_three11','Ch_three12',...
                        'Ch_three13','Ch_three14','Ch_three15','Ch_three16','Ch_three17','Ch_three18',...
                        'Ch_three19','Ch_three20')